//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MapEdit.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FORMVIEW                    101
#define IDR_MAINFRAME                   128
#define IDR_MAPEDITYPE                  129
#define IDD_DIALOG_SYS                  130
#define IDD_DIALOG_NPC                  131
#define IDD_DIALOG_ZOOM                 133
#define IDD_MODALESS                    135
#define IDD_DIALOG_QIEHUAN              136
#define IDD_DIALOG_DLG                  138
#define IDD_DIALOG_EDIT                 139
#define IDD_DIALOG_CONDITION            140
#define IDD_DIALOG_CONEDIT              141
#define IDD_DIALOG_EVENTEDIT            142
#define IDC_RADIO_KEZOU                 1000
#define IDC_RADIO_DAO                   1001
#define IDC_RADIO_QIEHUAN               1002
#define IDC_RADIO_MOVE                  1003
#define IDC_RADIO_DELPOINT              1004
#define IDC_RADIO_DELAREA               1005
#define IDC_RADIO_CHANGE                1006
#define IDC_COMBO_DAONEI                1007
#define IDC_COMBO_DAOWAI                1008
#define IDC_COMBO_WU                    1010
#define IDC_EDIT2                       1012
#define IDC_EDIT_TIME                   1012
#define IDC_EDIT_ZOOMOUT                1012
#define IDC_EDIT_EVENTDESCRIBE          1012
#define IDC_EDIT_CONDISCRIBE            1012
#define IDC_EDIT_EVENTDISCRIBE          1012
#define IDC_EDIT3                       1013
#define IDC_EDIT_EXPRESSION             1013
#define IDC_EDIT4                       1014
#define IDC_EDIT5                       1015
#define IDC_EDIT6                       1016
#define IDC_EDIT7                       1017
#define IDC_EDIT8                       1018
#define IDC_RADIO_ADDWU                 1020
#define IDC_COMBO_REN                   1021
#define IDC_EDIT9                       1022
#define IDC_EDIT10                      1023
#define IDC_EDIT11                      1024
#define IDC_EDIT12                      1025
#define IDC_EDIT13                      1026
#define IDC_EDIT14                      1027
#define IDC_EDIT15                      1028
#define IDC_EDIT16                      1029
#define IDC_RADIO_DELWU                 1030
#define IDC_RADIO_ADDREN                1031
#define IDC_RADIO_DELREN                1032
#define IDC_COMBOBOXEX1                 1033
#define IDC_COMBO_ATTRIB_NAME           1034
#define IDC_EDIT_ATTRIB_CODE            1036
#define IDC_SPINCODE                    1037
#define IDC_COLOR_R                     1038
#define IDC_SPIN_R                      1039
#define IDC_COLOR_G                     1040
#define IDC_SPIN_G                      1041
#define IDC_COLOR_B                     1042
#define IDC_SPIN_B                      1043
#define IDC_BUTTON_ADD                  1044
#define IDC_BUTTON_CANCEL               1045
#define IDC_BUTTON_SAVE                 1046
#define IDC_BUTTON_EXIT                 1047
#define IDC_SYSDEVICE                   1049
#define IDC_POINT                       1050
#define IDC_COMBO_STATE                 1051
#define IDC_SPIN_ZOOM                   1057
#define IDC_RADIO_FAR                   1058
#define IDC_RADIO_NEAR                  1059
#define IDC_BUTTON_TEST                 1060
#define IDC_BUTTON_ORGPOS               1063
#define IDC_ORGPOS                      1064
#define IDC_BUTTON_ZOOM                 1069
#define IDC_NPCZOOM                     1070
#define IDC_EDIT_ZOOMIN                 1071
#define IDC_RADIO_MOVEWUPOINT           1072
#define IDC_RADIO_DELWUPOINT            1073
#define IDC_RADIO_MOVERENPOINT          1074
#define IDC_RADIO_DELRENPOINT           1075
#define IDC_EDIT_QIEHUANCODE            1076
#define IDC_COMBO_QIEHUANSELECT         1077
#define IDC_BUTTON_DLG                  1078
#define IDC_BUTTON_CONDITION            1079
#define IDC_RADIO_NPC                   1080
#define IDC_RADIO_MAIN                  1081
#define IDC_EDIT_DLG                    1083
#define IDC_COMBO_CHOOSE                1085
#define IDC_RADIO_DLG                   1086
#define IDC_BUTTON_INSERT               1088
#define IDC_BUTTON_DELETE               1089
#define IDC_BUTTON_EDIT                 1091
#define IDC_LIST_STATION                1094
#define IDC_BUTTON_STATION              1095
#define IDC_BUTTON_STAEDIT              1096
#define IDC_BUTTON_STADELETE            1097
#define IDC_BUTTON_OK                   1098
#define IDC_STATIC_USE                  1099
#define IDC_EDIT_CONDESCRIBE            1112
#define IDC_LIST_CONDITION              1116
#define IDC_LIST_EVENT                  1117
#define IDC_BUTTON_CONOK                1122
#define IDC_BUTTON_EVENTOK              1123
#define IDC_BUTTON_CONDEL               1124
#define IDC_BUTTON_CONEDIT              1125
#define IDC_BUTTON_EVENTDEL             1126
#define IDC_BUTTON_EVENTEDIT            1127
#define IDC_EDIT_CONID                  1129
#define IDC_EDIT_EVENTID                1130
#define IDC_BUTTON1                     1131
#define IDC_LIST_FACE                   1132
#define IDC_LIST_DLG                    1133
#define ID_FILE_SAVESCENE               32771
#define ID_SYSFILE_CREATE               32772
#define ID_SYSFILE_CHANGE               32773
#define ID_MODEL_ZOOM                   32774
#define ID_INDICATOR_MOUSE              59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1134
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
